version: "3.9"

services:
  database: 
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=133113
      - POSTGRES_DB=segunda-api
    volumes: 
      - pgdata:/data/postgres

  segunda-api:
    build: .
    container_name: segunda-api
    ports:
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/docker/segunda-api
      - /docker/segunda-api/node_modules
    links:
      - database
    depends_on: 
      - database

volumes: 
  pgdata:
    driver: local
  